### ISSUE TITLE
Code for AUC computation.

### ISSUE THREAD

**Issue by kennyseb** [immortal3/MLNet-Pytorch#1]
Hey, 

Can you share the code used for efficient AUC/other metrics computation in pyTorch? I tried writing few of my own, but I doubt they aren't efficient as to be computed with training.

Thanks!

**Comment by immortal3** [comment]
I haven't coded metrics. I uploaded the result to SALICON challenge which gave me those metrics (on test data).

**Comment by kennyseb** [comment]
Ohk, thanks!
